Creaction de grille : 

In [1]:
import numpy as np
import random
import matplotlib.pyplot as plt
from matplotlib.colors import ListedColormap
gamma = 0.95
alpha = 0.1
theta = 1e-6

In [2]:
def build_valid_actions(n, m):
    """
    Retourne une liste valid_actions de taille S=n*m,
    où valid_actions[s] est la liste des actions possibles depuis l'état s.
    Actions: 0=UP, 1=RIGHT, 2=DOWN, 3=LEFT
    """
    valid_actions = [[] for _ in range(n*m)]
    for r in range(n):
        for c in range(m):
            s = r*m + c
            if r > 0:     valid_actions[s].append(0)  # UP
            if c < m-1:   valid_actions[s].append(1)  # RIGHT
            if r < n-1:   valid_actions[s].append(2)  # DOWN
            if c > 0:     valid_actions[s].append(3)  # LEFT
    return valid_actions

In [3]:
n = 7
m = 7
grid = np.arange(n*m).reshape(n, m)
print(grid)
start_state = 48
goal_state = 0
holes = [6, 16, 28, 30, 33, 40,45]
S = n * m

reward = np.zeros(S, dtype=float)
terminal = np.zeros(S, dtype=bool)
for s in holes:
  reward[s] = -10
  terminal[s] = True
terminal[goal_state] = True
reward[goal_state] = +10
valid_actions = build_valid_actions(n, m)
def step_det(n, m, s, a):
    r, c = divmod(s, m)
    if a == 0:   r -= 1      # UP
    elif a == 1: c += 1      # RIGHT
    elif a == 2: r += 1      # DOWN
    else:        c -= 1      # LEFT
    return r*m + c


[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]


In [4]:
print("Start:", start_state)
print("Goal:", goal_state)
print("Holes:", holes)

for s in holes:
    print(f"État {s} est terminal ? ", terminal[s], " reward =", reward[s])


Start: 48
Goal: 0
Holes: [6, 16, 28, 30, 33, 40, 45]
État 6 est terminal ?  True  reward = -10.0
État 16 est terminal ?  True  reward = -10.0
État 28 est terminal ?  True  reward = -10.0
État 30 est terminal ?  True  reward = -10.0
État 33 est terminal ?  True  reward = -10.0
État 40 est terminal ?  True  reward = -10.0
État 45 est terminal ?  True  reward = -10.0
