In [1]:
%run "creation_grille.ipynb"

[[ 0  1  2  3  4  5  6]
 [ 7  8  9 10 11 12 13]
 [14 15 16 17 18 19 20]
 [21 22 23 24 25 26 27]
 [28 29 30 31 32 33 34]
 [35 36 37 38 39 40 41]
 [42 43 44 45 46 47 48]]
Start: 48
Goal: 0
Holes: [6, 16, 28, 30, 33, 40, 45]
État 6 est terminal ?  True  reward = -10.0
État 16 est terminal ?  True  reward = -10.0
État 28 est terminal ?  True  reward = -10.0
État 30 est terminal ?  True  reward = -10.0
État 33 est terminal ?  True  reward = -10.0
État 40 est terminal ?  True  reward = -10.0
État 45 est terminal ?  True  reward = -10.0


In [2]:
def epsilon_greedy(Q, s, valid_actions, epsilon):
    if random.random() < epsilon:
        return random.choice(valid_actions[s])
    else:
        # action qui maximise Q(s,a)
        return max(valid_actions[s], key=lambda a: Q[s,a])

In [3]:
def q_learning(n, m, valid_actions, terminal, reward,
               alpha=0.1, gamma=0.95,
               epsilon=0.1,
               episodes=5000,
               max_steps=200):

    S = n*m
    Q = np.zeros((S, 4))  # 4 actions

    for ep in range(episodes):

        s = start_state  # on commence toujours au start

        for step in range(max_steps):

            # choisir action
            a = epsilon_greedy(Q, s, valid_actions, epsilon)

            # transition
            s2 = step_det(n, m, s, a)

            # récompense
            r = reward[s2]

            # mise à jour Q-learning
            best_next = max([Q[s2,a2] for a2 in valid_actions[s2]]) if not terminal[s2] else 0

            Q[s,a] = Q[s,a] + alpha * (r + gamma * best_next - Q[s,a])

            s = s2

            if terminal[s]:
                break

    return Q

In [ ]:
alpha = 0.1
gamma = 0.95
epsilon = 0.5

Q_ql = q_learning(
    n=7, m=7,
    valid_actions=valid_actions,
    terminal=terminal,
    reward=reward,
    alpha=alpha,
    gamma=gamma,
    epsilon=epsilon,
    episodes=5000
)

print("Q-table obtenue :")
print(np.round(Q_ql, 3))
policy_ql = np.zeros(49, dtype=int)

for s in range(49):
    if not terminal[s]:
        policy_ql[s] = max(valid_actions[s], key=lambda a: Q_ql[s,a])
plot_policy_grid_clean(
    n=7,
    m=7,
    policy=policy_ql,
    holes=holes,
    goal_state=goal_state,
    start_state=start_state,
    title="Q-learning – Politique finale"
) 

Q-table obtenue :
[[  0.      0.      0.      0.   ]
 [  0.      9.025   9.025  10.   ]
 [  0.      8.574   8.574   9.5  ]
 [  0.      8.145   8.145   9.025]
 [  0.      7.738   7.738   8.574]
 [  0.    -10.      7.349   8.145]
 [  0.      0.      0.      0.   ]
 [  7.712   8.997   3.944   0.   ]
 [  9.5     8.573   8.562   8.496]
 [  9.025   8.145 -10.      9.025]
 [  8.574   7.738   7.738   8.574]
 [  8.145   7.351   7.351   8.145]
 [  7.731   6.981   6.983   7.738]
 [-10.      0.      6.449   7.351]
 [  3.315   7.293   0.516   0.   ]
 [  9.024  -8.332   5.475   3.691]
 [  0.      0.      0.      0.   ]
 [  8.145   7.351   7.351 -10.   ]
 [  7.738   6.983   6.983   7.738]
 [  7.351   6.634   6.634   7.351]
 [  6.983   0.      6.302   6.983]
 [  1.052   2.59   -1.9     0.   ]
 [  8.024   1.137   0.409   0.467]
 [ -4.686   7.276  -7.176   2.761]
 [  7.738   6.983   6.932   6.764]
 [  7.351   6.634   6.634   7.351]
 [  6.983   6.302 -10.      6.983]
 [  6.634   0.      5.987   6.634]
 [

NameError: name 'plot_policy_grid_clean' is not defined